### ISSUE TITLE
Saved image is never deleted

### ISSUE THREAD

**Issue by Coh3n** [coryalder/DMActivityInstagram#15]
My apologies if I'm wrong (I'm still new to iOS development), but I cannot find where you remove the image you saved to the device's temporary folder.

According to the Apple documentation you should always remove files from the temp/ directory when you're finished with them.

I would assume this could/should be done in the activityDidFinish: method.

**Comment by coryalder** [comment]
Interesting! I've always assumed the temp directory gets cleaned by the system at regular intervals and could be written to and then ignored. Could you point me in the direction of the Apple documentation you speak of? I can't find that reference.

[NSHipster](http://nshipster.com/nstemporarydirectory/) says tmp directories are cleaned up about every 3 days... that's a lot less often than I had assumed, so you're probably right that adding a cleanup would be good form.

**Comment by Coh3n** [comment]
Sure, I found it in the iOS Data Storage Guidelines:
https://developer.apple.com/icloud/documentation/data-storage/index.html

"Data that is used only temporarily should be stored in the <Application_Home>/tmp directory. Although these files are not backed up to iCloud, remember to delete those files when you are done with them so that they do not continue to consume space on the user’s device."

**Comment by coryalder** [comment]
I've pushed a fix and bumped the CocoaPod spec. Thanks, @Coh3n, for noticing this!
